name: DigitalClock
main: me.PerwinCZ.DigitalClock.Main
author: PerwinCZ
version: 1.6
commands:
  digitalclock:
    description: Use more arguments for this command
    usage: /digitalclock (arguments)
permissions:
  digitalclock.create:
    description: Allows you to create a new clock 
  digitalclock.remove:
    description: Allows you to remove an existing clock 
  digitalclock.rotate:
    description: Allows you to rotate an existing clock 
  digitalclock.material:
    description: Allows you to change the material of an existing clock 
  digitalclock.fill:
    description: Allows you to change the filling material of an existing clock 
  digitalclock.move:
    description: Allows you to move an existing clock to the clicked coords
  digitalclock.tp:
    description: Allows you to teleport self to an existing clock's location  
  digitalclock.stopclocks:
    description: Allows you to stop all clocks on the server     
  digitalclock.runclocks:
    description: Allows you to run all stopped clocks on the server  
  digitalclock.list:
    description: Allows you to show the list of existing clocks   
  digitalclock.reload:
    description: Allows you to reload config.yml file   
  digitalclock.help:
    description: Allows you to show the plugin command helper
  digitalclock.limit.*:
    description: Sets the limit of clock for player 
  digitalclock.addingminutes:
    description: Allows you to add minutes on your clock  
  digitalclock.toggleampm:
    description: Allows you to toggle showing AM/PM 
  digitalclock.toggleseconds:
    description: Allows you to toggle showing seconds    
  digitalclock.toggleingametime:
    description: Allows you to toggle showing of ingame time
  digitalclock.settime:
    description: Allows you to set time on specified clock
  digitalclock.toggleblinking:
    description: Allows you to toggle blinking of colon (:)
  digitalclock.setcountdown:
    description: Allows you to set countdown on clock
  digitalclock.disablecountdown:
    description: Allows you to disable countdown mode on clock   
  digitalclock.toggleingametime:
    description: Toggles showing of world (ingame) time   
    
    
                 